class_name Inspirations
extends RefCounted
## Os jogos clássicos que inspiraram cada jogo do Arcade (por "arg" do jogo): nome original,
## autores/editora e ano, uma pequena história e a página da Wikipédia. Os nomes são marcas dos
## respetivos donos; este projeto não tem qualquer ligação a eles. As histórias são traduzidas
## por I18n; "wiki" é a página em português (ou inglês), "wiki_en" e "wiki_es" para os outros idiomas.

const INFO := {
	"pong": {"name": "Pong", "by": "Atari, 1972",
		"story": "Criado por Allan Alcorn como exercício de treino pedido por Nolan Bushnell, fundador da Atari. A primeira máquina foi instalada num bar da Califórnia e conta-se que deixou de funcionar porque o mealheiro estava cheio de moedas. Foi o primeiro grande êxito comercial dos videojogos e deu início à era das máquinas de arcada.",
		"wiki": "https://pt.wikipedia.org/wiki/Pong", "wiki_en": "https://en.wikipedia.org/wiki/Pong", "wiki_es": "https://en.wikipedia.org/wiki/Pong"},
	"breakout": {"name": "Breakout", "by": "Atari, 1976",
		"story": "Ideia de Nolan Bushnell e Steve Bristow: um Pong para um só jogador, em que a bola parte uma parede de tijolos. O protótipo foi desenhado por Steve Wozniak, com Steve Jobs, pouco antes de fundarem a Apple. Inspirou dezenas de sucessores, como o Arkanoid.",
		"wiki": "https://pt.wikipedia.org/wiki/Breakout_(jogo_eletr%C3%B4nico)", "wiki_en": "https://en.wikipedia.org/wiki/Breakout_(video_game)", "wiki_es": "https://es.wikipedia.org/wiki/Breakout_(videojuego)"},
	"invaders": {"name": "Space Invaders", "by": "Taito, 1978",
		"story": "Criado por Tomohiro Nishikado, que também construiu o hardware, inspirado no Breakout. Os invasores aceleram à medida que vão sendo abatidos porque o processador tinha menos figuras para desenhar — um acaso que se tornou a sua marca. Foi um fenómeno mundial e popularizou a ideia de bater o recorde.",
		"wiki": "https://en.wikipedia.org/wiki/Space_Invaders", "wiki_en": "https://en.wikipedia.org/wiki/Space_Invaders", "wiki_es": "https://en.wikipedia.org/wiki/Space_Invaders"},
	"asteroids": {"name": "Asteroids", "by": "Atari, 1979",
		"story": "Desenhado por Lyle Rains e Ed Logg, com gráficos vetoriais de traço luminoso e uma nave que se move com inércia, como no espaço. Foi o jogo de arcada mais vendido da Atari e um dos primeiros a deixar o jogador escrever as suas iniciais na tabela de recordes.",
		"wiki": "https://en.wikipedia.org/wiki/Asteroids_(video_game)", "wiki_en": "https://en.wikipedia.org/wiki/Asteroids_(video_game)", "wiki_es": "https://en.wikipedia.org/wiki/Asteroids_(video_game)"},
	"galaxian": {"name": "Galaxian", "by": "Namco, 1979",
		"story": "A resposta da Namco ao Space Invaders: os alienígenas saem da formação e mergulham sobre o jogador em voos curvos. Foi um dos primeiros jogos com gráficos totalmente a cores e teve como sucessor o famoso Galaga (1981).",
		"wiki": "https://en.wikipedia.org/wiki/Galaxian", "wiki_en": "https://en.wikipedia.org/wiki/Galaxian", "wiki_es": "https://en.wikipedia.org/wiki/Galaxian"},
	"firefly": {"name": "Pac-Man", "by": "Namco, 1980",
		"story": "Criado por Toru Iwatani para agradar a um público mais vasto do que os jogos de tiro, incluindo as mulheres. Cada um dos quatro fantasmas persegue o jogador à sua maneira. Diz-se que a forma da personagem nasceu de uma pizza a que faltava uma fatia. É um dos jogos de arcada mais lucrativos de sempre.",
		"wiki": "https://en.wikipedia.org/wiki/Pac-Man", "wiki_en": "https://en.wikipedia.org/wiki/Pac-Man", "wiki_es": "https://es.wikipedia.org/wiki/Pac-Man"},
	"frogger": {"name": "Frogger", "by": "Konami, 1981",
		"story": "Desenvolvido pela Konami e distribuído pela Sega fora do Japão: levar sapos a casa atravessando uma estrada movimentada e um rio cheio de troncos e tartarugas. Original, sem tiros nem naves, tornou-se um dos símbolos da época de ouro das arcadas.",
		"wiki": "https://en.wikipedia.org/wiki/Frogger", "wiki_en": "https://en.wikipedia.org/wiki/Frogger", "wiki_es": "https://en.wikipedia.org/wiki/Frogger"},
	"centipede": {"name": "Centipede", "by": "Atari, 1981",
		"story": "Desenhado por Ed Logg e Dona Bailey, uma das primeiras mulheres a criar videojogos. Joga-se com uma bola de controlo (trackball) num campo de cogumelos onde desce uma centopeia que se divide quando é atingida. Foi especialmente popular entre as jogadoras.",
		"wiki": "https://en.wikipedia.org/wiki/Centipede_(video_game)", "wiki_en": "https://en.wikipedia.org/wiki/Centipede_(video_game)", "wiki_es": "https://es.wikipedia.org/wiki/Centipede_(videojuego)"},
	"penetrator": {"name": "Penetrator", "by": "Melbourne House, 1982",
		"story": "Jogo para o ZX Spectrum de Philip Mitchell (coautor do célebre The Hobbit), inspirado no Scramble (Konami, 1981): uma nave avança por cavernas a disparar e a bombardear. Trazia um editor para o jogador desenhar as suas próprias paisagens, algo raro na época.",
		"wiki": "https://en.wikipedia.org/wiki/Penetrator_(video_game)", "wiki_en": "https://en.wikipedia.org/wiki/Penetrator_(video_game)", "wiki_es": "https://en.wikipedia.org/wiki/Penetrator_(video_game)"},
	"chuckie": {"name": "Chuckie Egg", "by": "A&F Software, 1983",
		"story": "Escrito por Nigel Alderton, ainda adolescente, para o ZX Spectrum e o BBC Micro. O agricultor Harry apanha ovos em plataformas e escadas, fugindo das galinhas, enquanto um pato gigante espera na gaiola. Foi um dos jogos mais queridos dos computadores britânicos dos anos 80.",
		"wiki": "https://en.wikipedia.org/wiki/Chuckie_Egg", "wiki_en": "https://en.wikipedia.org/wiki/Chuckie_Egg", "wiki_es": "https://en.wikipedia.org/wiki/Chuckie_Egg"},
	"jetpac": {"name": "Jetpac", "by": "Ultimate Play the Game, 1983",
		"story": "O primeiro jogo da Ultimate, dos irmãos Tim e Chris Stamper, para o ZX Spectrum de 16K. Um astronauta com mochila-foguete monta a nave, enche-a de combustível e defende-se dos alienígenas. Os Stamper fundariam mais tarde a Rare.",
		"wiki": "https://en.wikipedia.org/wiki/Jetpac", "wiki_en": "https://en.wikipedia.org/wiki/Jetpac", "wiki_es": "https://en.wikipedia.org/wiki/Jetpac"},
	"relics": {"name": "Knight Lore", "by": "Ultimate Play the Game, 1984",
		"story": "Revolucionou os computadores de 8 bits com salas em perspetiva isométrica que pareciam 3D. O aventureiro Sabreman transforma-se em lobisomem ao anoitecer e tem 40 dias para encontrar a cura num castelo cheio de armadilhas. Foi imitado por muitos jogos isométricos que se seguiram.",
		"wiki": "https://en.wikipedia.org/wiki/Knight_Lore", "wiki_en": "https://en.wikipedia.org/wiki/Knight_Lore", "wiki_es": "https://en.wikipedia.org/wiki/Knight_Lore"},
	"blocks": {"name": "Tetris", "by": "Alexey Pajitnov, 1984",
		"story": "Criado em Moscovo por Alexey Pajitnov, num computador soviético Electronika 60 que só mostrava texto — por isso as peças eram feitas de parênteses retos. O nome junta \"tetra\" (quatro) e ténis. A versão de 1989 para a Game Boy tornou-o um dos jogos mais vendidos de sempre.",
		"wiki": "https://en.wikipedia.org/wiki/Tetris", "wiki_en": "https://en.wikipedia.org/wiki/Tetris", "wiki_es": "https://en.wikipedia.org/wiki/Tetris"},
	"school": {"name": "Skool Daze", "by": "Microsphere, 1985",
		"story": "De David Reidy e Keith Warrington, para o ZX Spectrum. O aluno Eric tem de tirar o boletim do cofre da escola: acerta em todos os escudos e descobre o segredo com os professores, cumprindo o horário das aulas para não acumular linhas de castigo. Era possível mudar o nome a todas as personagens. Seguiu-se o Back to Skool.",
		"wiki": "https://en.wikipedia.org/wiki/Skool_Daze", "wiki_en": "https://en.wikipedia.org/wiki/Skool_Daze", "wiki_es": "https://en.wikipedia.org/wiki/Skool_Daze"},
	"outrun": {"name": "Out Run", "by": "Sega, 1986",
		"story": "Criado por Yu Suzuki: um descapotável vermelho, uma estrada à beira-mar com bifurcações e a possibilidade de escolher a música no rádio. A versão de luxo tinha um assento que se mexia com as curvas. Foi um dos jogos de arcada mais populares da década.",
		"wiki": "https://en.wikipedia.org/wiki/Out_Run", "wiki_en": "https://en.wikipedia.org/wiki/Out_Run", "wiki_es": "https://en.wikipedia.org/wiki/Out_Run"},
	"vale": {"name": "The Legend of Zelda", "by": "Nintendo, 1986",
		"story": "Criado por Shigeru Miyamoto e Takashi Tezuka, inspirado nas explorações de infância de Miyamoto pelos campos e grutas perto de Quioto. Um mundo aberto para explorar, masmorras com chaves e tesouros, e um dos primeiros jogos de consola a guardar o progresso.",
		"wiki": "https://pt.wikipedia.org/wiki/The_Legend_of_Zelda_(jogo_eletr%C3%B4nico)", "wiki_en": "https://en.wikipedia.org/wiki/The_Legend_of_Zelda_(video_game)", "wiki_es": "https://en.wikipedia.org/wiki/The_Legend_of_Zelda_(video_game)"},
	"palace": {"name": "Prince of Persia", "by": "Jordan Mechner, 1989",
		"story": "Criado por Jordan Mechner para o Apple II. Os movimentos do herói foram desenhados a partir de filmagens do irmão a correr e a saltar, o que lhe deu uma animação de um realismo nunca visto. Uma hora para escapar das masmorras e salvar a princesa do vizir Jaffar.",
		"wiki": "https://pt.wikipedia.org/wiki/Prince_of_Persia_(jogo_eletr%C3%B4nico_de_1989)", "wiki_en": "https://en.wikipedia.org/wiki/Prince_of_Persia_(1989_video_game)", "wiki_es": "https://en.wikipedia.org/wiki/Prince_of_Persia_(1989_video_game)"},
	"flock": {"name": "Lemmings", "by": "DMA Design / Psygnosis, 1991",
		"story": "Nasceu em Dundee, na Escócia, de um pequeno teste de animação de bonecos com poucos píxeis. As criaturinhas avançam sem medo de nada e o jogador tem de lhes dar funções para as salvar. A DMA Design viria depois a criar o Grand Theft Auto.",
		"wiki": "https://pt.wikipedia.org/wiki/Lemmings_(jogo_eletr%C3%B4nico)", "wiki_en": "https://en.wikipedia.org/wiki/Lemmings_(video_game)", "wiki_es": "https://en.wikipedia.org/wiki/Lemmings_(video_game)"},
}
